/// This module stores immutable proof of AI medical analysis on-chain.
/// It creates on-chain records (NFTs) that prove a diagnosis was made by Dr. Sui's AI system.
///
/// Why we store hash instead of actual medical data:
/// 1. Privacy - Medical data is sensitive and shouldn't be public on-chain
/// 2. Gas costs - Storing full reports would be prohibitively expensive
/// 3. Verifiability - Hash allows verification without exposing data
///    (off-chain systems can verify hash matches the original report)

module dr_sui::record;

use std::string::String;
use sui::object::{Self, UID};
use sui::tx_context::{Self, TxContext};
use sui::transfer;

/// A Diagnosis struct represents an immutable record of an AI medical diagnosis.
/// Each diagnosis is a unique object (NFT) transferred to the patient.
///
/// Fields:
/// - id: Unique identifier (UID) generated by Sui
/// - patient: Wallet address of the patient who receives this diagnosis record
/// - report_hash: SHA256 hash of the AI-generated medical report (for verification)
/// - ai_model: Name of the AI model used (e.g., "llama-3.2-vision", "llama-3.2-90b")
/// - severity: Severity level: "NORMAL", "MEDIUM", or "HIGH"
/// - timestamp: Unix timestamp when the diagnosis was created
struct Diagnosis has key, store {
    id: UID,
    patient: address,
    report_hash: vector<u8>,
    ai_model: String,
    severity: String,
    timestamp: u64,
}

/// Public entry function to mint a new Diagnosis record.
/// This creates an on-chain proof that a diagnosis was made.
///
/// # Parameters:
/// - patient: Address of the patient who will receive this diagnosis record
/// - report_hash: SHA256 hash of the AI-generated medical report (32 bytes)
/// - ai_model: Name/identifier of the AI model used for analysis
/// - severity: Severity level ("NORMAL", "MEDIUM", "HIGH")
/// - timestamp: Unix timestamp when diagnosis was created
/// - ctx: Transaction context (automatically provided by Sui)
///
/// # Effects:
/// - Creates a new Diagnosis object
/// - Transfers it to the patient's address
/// - Object becomes owned by the patient and can be transferred/sold later
public entry function mint_diagnosis(
    patient: address,
    report_hash: vector<u8>,
    ai_model: String,
    severity: String,
    timestamp: u64,
    ctx: &mut TxContext
) {
    // Create a new Diagnosis object with unique ID
    let diagnosis = Diagnosis {
        id: object::new(ctx),
        patient,
        report_hash,
        ai_model,
        severity,
        timestamp,
    };

    // Transfer the Diagnosis object to the patient
    // The patient now owns this on-chain proof of their diagnosis
    transfer::transfer(diagnosis, patient);
}

